version: "3"
services:
  udagram-reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: titanknight777/udagram-reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: titanknight777/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: titanknight777/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: titanknight777/uudagram-frontend